ARG VERSION=Latest

# build backend
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

COPY nhitomi-idx/nhitomi/nhitomi.csproj ./
RUN dotnet restore

COPY nhitomi-idx/nhitomi ./
RUN dotnet build -c Release -o build --no-restore

# build final image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app

COPY --from=build /app/build ./

ARG VERSION
ARG SENTRY_DSN

ENV ASPNETCORE_ENVIRONMENT Production
ENV ASPNETCORE_APP_VERSION $VERSION
ENV SENTRY_ENVIRONMENT production
ENV SENTRY_DSN $SENTRY_DSN

EXPOSE 80

ENTRYPOINT ["dotnet", "nhitomi.dll"]
