# retrieve git commit information
FROM alpine:latest AS git
COPY .git ./.git

RUN apk add --no-cache git
RUN git log -1 --date=iso-strict > version.txt

# build backend
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS idx
WORKDIR /app

COPY nhitomi-idx/nhitomi/nhitomi.csproj ./
RUN dotnet restore

COPY nhitomi-idx/nhitomi ./
RUN dotnet build -c Release -o build --no-restore

# generate api spec file
RUN dotnet "build/nhitomi.dll" -- --generate-spec > apispec.json

# build frontend
FROM node:lts-alpine AS web
WORKDIR /app

COPY nhitomi-web/package.json nhitomi-web/yarn.lock ./
COPY scripts ../scripts/
RUN yarn

COPY --from=idx /app/apispec.json ./

# java 8 required by openapi-generator
RUN apk add --no-cache openjdk8-jre
RUN yarn genclient apispec.json

COPY nhitomi-web ./
RUN yarn build

# build final image
FROM mcr.microsoft.com/dotnet/aspnet:5.0 as app
WORKDIR /app

COPY --from=git version.txt ./
COPY --from=idx /app/build ./
COPY --from=web /app/build ./static/

ENV ASPNETCORE_ENVIRONMENT Production
ENTRYPOINT ["dotnet", "nhitomi.dll"]
