FROM mcr.microsoft.com/dotnet/sdk:5.0

WORKDIR /app
COPY nhitomi-idx ./

RUN dotnet build nhitomi.Tests

ENTRYPOINT ["dotnet", "test", "--no-build", "--no-restore", "--list-tests", "--verbosity", "normal", "nhitomi.Tests"]
